meta_product_name: "Blindly"
meta_title: "Blindly - Be your own matchmaker"
meta_description: "Blindly is a web dating app where the focus is on building genuine connections based on shared interests. True bonds are established through conversation, not solely on appearance."
meta_image: "blindly-og-img.png" # should exist in `app/assets/images/`


